# Лабораторная работа №5
**Задача 1.** <br>
Разделить таблицу данных так, чтобы в обучающую выборку попало 66% наблюдений, а в тестовую выборку 33% наблюдений.<br>

**Задача 2.** <br>
Разделить таблицу данных на четыре одинаковых части.<br>

**Задача 3.** <br>
Разделить таблицу данных на две стратифицированные подвыборки. По переменным кока-кола и минералка.

In [1]:
# Импортируем библиотеки
import random
import pandas as pd
import numpy as np

from sklearn.model_selection import train_test_split

In [2]:
# Загружаем данные
df = pd.read_csv('beverage_r.csv', sep=";", index_col='numb.obs')
df.head()

          COKE  D_COKE  D_PEPSI  D_7UP  PEPSI  SPRITE  TAB  SEVENUP
numb.obs
1            1       0        0      0      1       1    0        1
2            1       0        0      0      1       0    0        0
3            1       0        0      0      1       0    0        0
4            0       1        0      1      0       0    1        0
5            1       0        0      0      1       0    0        0

In [3]:
num_of_lines = len(df.index)
num_of_lines

34

### Задача 1. <br>
Разделить таблицу данных так, чтобы в обучающую выборку попало 66% наблюдений, а в тестовую выборку 33% наблюдений.<br>

In [4]:
#  Перемешиваем индексы
random.seed(42)
new_index = np.random.permutation(num_of_lines)
new_index

array([27, 26, 29, 30, 22,  5, 33, 25,  4, 17, 23, 32, 28, 13, 24, 21, 12,
        7,  8, 15,  3,  9, 11, 10, 18, 14, 31, 20, 19,  6,  0,  2,  1, 16])

In [5]:
# Задаем размеры обучающей
train_size = int(0.66*num_of_lines)
train_size

22

In [6]:
train_df = df.iloc[new_index[:train_size]]
train_df

          COKE  D_COKE  D_PEPSI  D_7UP  PEPSI  SPRITE  TAB  SEVENUP
numb.obs
28           1       0        0      0      0       1    0        1
27           0       1        0      0      0       0    1        0
30           0       1        1      0      0       0    1        0
31           1       0        0      0      1       0    0        1
23           0       1        0      1      0       0    1        0
6            1       0        0      0      1       1    0        0
34           0       1        1      1      0       0    1        0
26           0       1        0      1      0       0    1        0
5            1       0        0      0      1       0    0        0
18           1       1        0      0      1       0    0        0
24           1       1        0      0      1       0    0        0
33           1       0        0      0      1       0    0        1
29           1       0        0      0      0       1    0        0
14           1       0        0      0      0       1    0        0
25           0       1        1      1      0       0    0        0
22           1       0        0      0      1       0    0        0
13           0       0        1      1      0       1    0        1
8            1       1        0      0      1       1    0        1
9            1       1        0      0      0       1    1        1
16           0       0        0      0      1       1    0        0
4            0       1        0      1      0       0    1        0
10           1       0        0      0      1       0    0        1

In [7]:
test_df = df.iloc[new_index[train_size:]]
test_df

          COKE  D_COKE  D_PEPSI  D_7UP  PEPSI  SPRITE  TAB  SEVENUP
numb.obs
12           0       1        0      0      0       0    1        0
11           1       0        0      0      1       1    0        0
19           1       0        0      0      0       0    0        1
15           0       1        1      0      0       0    1        0
32           0       1        1      0      0       0    1        0
21           1       0        0      0      1       0    0        0
20           1       1        1      0      1       0    0        0
7            0       1        1      1      0       0    1        0
1            1       0        0      0      1       1    0        1
3            1       0        0      0      1       0    0        0
2            1       0        0      0      1       0    0        0
17           0       1        0      0      0       1    0        0

In [8]:
# Проверяем соотношение выборок
print(f'Размер обучающей выборки: {len(train_df.index)}, размер тестовой выборки: {len(test_df.index)}')
print(f'Соотношение выборок: {np.round(len(train_df.index)/len(df), 2)}, {np.round(len(test_df.index)/len(df), 2)}')

Размер обучающей выборки: 22, размер тестовой выборки: 12
Соотношение выборок: 0.65, 0.35

In [9]:
# Теперь попробуем выбрать с помощью sklearn
train_df_sk, test_df_sk = train_test_split(df, test_size=0.33, shuffle=True)

In [10]:
# Проверяем соотношение выборок
print(f'Размер обучающей выборки: {len(train_df_sk.index)}, размер тестовой выборки: {len(test_df_sk.index)}')
print(f'Соотношение выборок: {np.round(len(train_df_sk.index)/len(df), 2)}, {np.round(len(test_df_sk.index)/len(df), 2)}')

Размер обучающей выборки: 22, размер тестовой выборки: 12
Соотношение выборок: 0.65, 0.35

### Задача 2. <br>
Разделить таблицу данных на четыре одинаковых части.<br>

In [11]:
#  Чтобы точнее разделить таблицу на четыре одинаковые части используем квартили
r1 = np.random.uniform(low = 0.0, high=1.0, size=len(df))

q1 = np.quantile(r1, 0.25)
q2 = np.quantile(r1, 0.5)
q3 = np.quantile(r1, 0.75)

q1, q2, q3

(np.float64(0.3126570570261019),
 np.float64(0.48273743232533556),
 np.float64(0.7200436559274783))

In [12]:
df_1 = df.iloc[r1<q1]
df_2 = df.iloc[(r1>q1) & (r1<q2)]
df_3 = df.iloc[(r1>q2) & (r1<q3)]
df_4 = df.iloc[r1>q3]

In [13]:
df_1

          COKE  D_COKE  D_PEPSI  D_7UP  PEPSI  SPRITE  TAB  SEVENUP
numb.obs
5            1       0        0      0      1       0    0        0
7            0       1        1      1      0       0    1        0
9            1       1        0      0      0       1    1        1
12           0       1        0      0      0       0    1        0
13           0       0        1      1      0       1    0        1
14           1       0        0      0      0       1    0        0
15           0       1        1      0      0       0    1        0
25           0       1        1      1      0       0    0        0
31           1       0        0      0      1       0    0        1

In [14]:
df_2

          COKE  D_COKE  D_PEPSI  D_7UP  PEPSI  SPRITE  TAB  SEVENUP
numb.obs
2            1       0        0      0      1       0    0        0
8            1       1        0      0      1       1    0        1
10           1       0        0      0      1       0    0        1
11           1       0        0      0      1       1    0        0
26           0       1        0      1      0       0    1        0
27           0       1        0      0      0       0    1        0
30           0       1        1      0      0       0    1        0
33           1       0        0      0      1       0    0        1

In [15]:
df_3

          COKE  D_COKE  D_PEPSI  D_7UP  PEPSI  SPRITE  TAB  SEVENUP
numb.obs
4            0       1        0      1      0       0    1        0
6            1       0        0      0      1       1    0        0
19           1       0        0      0      0       0    0        1
20           1       1        1      0      1       0    0        0
21           1       0        0      0      1       0    0        0
22           1       0        0      0      1       0    0        0
23           0       1        0      1      0       0    1        0
29           1       0        0      0      0       1    0        0

In [16]:
df_4

          COKE  D_COKE  D_PEPSI  D_7UP  PEPSI  SPRITE  TAB  SEVENUP
numb.obs
1            1       0        0      0      1       1    0        1
3            1       0        0      0      1       0    0        0
16           0       0        0      0      1       1    0        0
17           0       1        0      0      0       1    0        0
18           1       1        0      0      1       0    0        0
24           1       1        0      0      1       0    0        0
28           1       0        0      0      0       1    0        1
32           0       1        1      0      0       0    1        0
34           0       1        1      1      0       0    1        0

In [17]:
# Проверяем соотношение выборок
print(f'Размер каждой выборки: {len(df_1)}, {len(df_2)}, {len(df_3)}, {len(df_4)}')
print(f'Соотношение выборок: {np.round(len(df_1.index)/len(df), 2)}, {np.round(len(df_2)/len(df), 2)}, {np.round(len(df_3)/len(df), 2)}, {np.round(len(df_4)/len(df), 2)}')

Размер каждой выборки: 9, 8, 8, 9
Соотношение выборок: 0.26, 0.24, 0.24, 0.26

### Задача 3 <br>
Разделить таблицу данных на две стратифицированные подвыборки. По переменным кока-кола и минералка.

In [18]:
# Создаем объединенную колонку по переменным COKE и TAB
df['strat_coke_tab'] = df['COKE'].astype(str) + '_' + df['TAB'].astype(str)
df.head()

,COKE,D_COKE,D_PEPSI,D_7UP,PEPSI,SPRITE,TAB,SEVENUP,strat_coke_tab
numb.obs,,,,,,,,,
1,1,0,0,0,1,1,0,1,1_0
2,1,0,0,0,1,0,0,0,1_0
3,1,0,0,0,1,0,0,0,1_0
4,0,1,0,1,0,0,1,0,0_1
5,1,0,0,0,1,0,0,0,1_0

In [19]:
# Проверяем распределение данных
df.strat_coke_tab.value_counts()

strat_coke_tab
1_0    19
0_1    10
0_0     4
1_1     1
Name: count, dtype: int64

Так как присутствует группа с 1 значением, то при автоматическом (используя sklearn) делении на равные выборки выходит ошибка: <br>
```train_df, test_df = train_test_split(df, test_size = 0.5, stratify=df['strat_coke_tab'], shuffle=True, random_state=42)```

> ValueError: The least populated class in y has only 1 member, which is too few. The minimum number of groups for any class cannot be less than 2.

В таком случае будем делить вручную и при 1 значении отправлять в обучающую выборку.

In [21]:
train_strat = []
test_strat = []

for i in df['strat_coke_tab'].unique():
    if len(df[df['strat_coke_tab'] == i].index) == 1:
        train_strat.append(df.loc[df[df['strat_coke_tab'] == i].index])
        continue

    group_test = int(len(df[df['strat_coke_tab'] == i].index) * 0.5)
    indx = np.random.permutation(df[df['strat_coke_tab'] == i].index)
    train_strat.append(df.loc[indx[:group_test]])
    test_strat.append(df.loc[indx[group_test:]])

train_strat_df = pd.concat(train_strat)
test_strat_df = pd.concat(test_strat)

In [22]:
train_strat_df.head()

,COKE,D_COKE,D_PEPSI,D_7UP,PEPSI,SPRITE,TAB,SEVENUP,strat_coke_tab
numb.obs,,,,,,,,,
6,1,0,0,0,1,1,0,0,1_0
21,1,0,0,0,1,0,0,0,1_0
8,1,1,0,0,1,1,0,1,1_0
3,1,0,0,0,1,0,0,0,1_0
33,1,0,0,0,1,0,0,1,1_0

In [23]:
test_strat_df.head()

,COKE,D_COKE,D_PEPSI,D_7UP,PEPSI,SPRITE,TAB,SEVENUP,strat_coke_tab
numb.obs,,,,,,,,,
14,1,0,0,0,0,1,0,0,1_0
28,1,0,0,0,0,1,0,1,1_0
11,1,0,0,0,1,1,0,0,1_0
31,1,0,0,0,1,0,0,1,1_0
2,1,0,0,0,1,0,0,0,1_0

In [24]:
# Убедимся, что единственное значение попало в обучающую выборку
train_strat_df['strat_coke_tab'].value_counts()

strat_coke_tab
1_0    9
0_1    5
0_0    2
1_1    1
Name: count, dtype: int64

In [25]:
# Убедимся, что единственное значение не попало в тестовую выборку
test_strat_df['strat_coke_tab'].value_counts()

strat_coke_tab
1_0    10
0_1     5
0_0     2
Name: count, dtype: int64

In [26]:
# Удаляем столбец со стратифицированными данными
train_strat_df.drop(columns=['strat_coke_tab'], inplace=True)
test_strat_df.drop(columns=['strat_coke_tab'], inplace=True)

In [27]:
# Проверяем соотношение выборок
print(f'Размер обучающей выборки: {len(train_strat_df.index)}, размер тестовой выборки: {len(test_strat_df.index)}')
print(f'Соотношение выборок: {np.round(len(train_strat_df.index)/len(df), 2)}, {np.round(len(test_strat_df.index)/len(df), 2)}')

Размер обучающей выборки: 17, размер тестовой выборки: 17
Соотношение выборок: 0.5, 0.5